# DE with Python

In these exercises, you will practice working with **Pandas DataFrames**, extracting subsets of data using Python APIs, connecting to an **SQLite** database, running SQL queries, and converting query results into Pandas DataFrames.

Some cells contain code to run and understand. Cells marked **TODO** are exercises for you to complete.

> This notebook is suitable for Google Colab. The paths assume the usual `sample_data/` directory.

## 1. Imports

In [ ]:
import pandas as pd
import csv
import sqlite3
from sqlite3 import Error

## 2. Creating DataFrames

### Creating a DataFrame from a dictionary / Pandas Series-like columns

In [ ]:
data = {
    'State': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'Year': [2000, 2001, 2002, 2001, 2002, 2003],
    'Population': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
df = pd.DataFrame(data)
df

    State  Year  Population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2001         2.4
4  Nevada  2002         2.9
5  Nevada  2003         3.2

### Creating a DataFrame from a data matrix

In [ ]:
data = [
    ['Ohio', 2000, 1.5], ['Ohio', 2001, 1.7], ['Ohio', 2002, 3.6],
    ['Nevada', 2001, 2.4], ['Nevada', 2002, 2.9], ['Nevada', 2003, 3.2]
]
cols = ['State', 'Year', 'Population']
df = pd.DataFrame(data, columns=cols)
df

    State  Year  Population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2001         2.4
4  Nevada  2002         2.9
5  Nevada  2003         3.2

### Number of columns and rows

In [ ]:
print("number of columns =", len(df.columns))
print("number of rows =", len(df))

number of columns = 3
number of rows = 6

### Creating a DataFrame from a CSV file

In [ ]:
df = pd.read_csv(
    filepath_or_buffer='sample_data/california_housing_train.csv',
    delimiter=',',
    doublequote=True,
    quotechar='"',
    na_values=['na', '-', '.', ''],
    quoting=csv.QUOTE_MINIMAL,
    encoding='ISO-8859-1'
)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

## 3. Extracting Data from Pandas DataFrames

Use `california_housing_train.csv` for the following exercises.

### Extracting rows and blocks

In [ ]:
df.info()

n = 4
dfh = df.head(n)
dft = df.tail(n)
top_left_corner_df = df.iloc[:5, :5]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

**TODO:** Display the contents of `dfh`, `dft`, and `top_left_corner_df`.

In [ ]:
# TODO
# display(dfh)
# display(dft)
# display(top_left_corner_df)

### Extracting columns

In [ ]:
col_set = df.iloc[:, 5:9]
col_set

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 4 columns]

This extracts columns 6, 7, 8, and 9 when counting columns from 1. For non-consecutive columns, pass a list of column indices to `iloc`.

### Extracting rows

**TODO:** Extract rows 11, 13, and 15 from the DataFrame. Remember that Python uses zero-based indexing.

In [ ]:
# TODO: extract rows 11, 13, and 15
# selected_rows = ...
# selected_rows

### Extracting rows satisfying a condition

In [ ]:
df.loc[
    df['total_rooms'] > 5000,
    ['longitude', 'latitude', 'total_rooms', 'median_house_value']
]

       longitude  latitude  total_rooms  median_house_value
0        -114.31     34.19       5612.0             66900.0
1        -114.47     34.40       7650.0             80100.0
133      -116.06     34.15      10377.0             66800.0
135      -116.09     34.15       9444.0             65600.0
167      -116.24     33.72       5236.0             93400.0
...          ...       ...          ...                 ...
16824    -123.22     39.28       5569.0            142900.0
16838    -123.34     39.10       5372.0            131100.0
16854    -123.49     38.70       5409.0            295400.0
16859    -123.59     38.80       5202.0            176100.0
16986    -124.19     40.73       5694.0             90100.0

[1455 rows x 4 columns]

Using positional column indices with `iloc` requires a different pattern because `loc` expects column labels. For example:

In [ ]:
df.loc[df['total_rooms'] > 5000].iloc[:, [0, 1, 3, 8]]

       longitude  latitude  total_rooms  median_house_value
0        -114.31     34.19       5612.0             66900.0
1        -114.47     34.40       7650.0             80100.0
133      -116.06     34.15      10377.0             66800.0
135      -116.09     34.15       9444.0             65600.0
167      -116.24     33.72       5236.0             93400.0
...          ...       ...          ...                 ...
16824    -123.22     39.28       5569.0            142900.0
16838    -123.34     39.10       5372.0            131100.0
16854    -123.49     38.70       5409.0            295400.0
16859    -123.59     38.80       5202.0            176100.0
16986    -124.19     40.73       5694.0             90100.0

[1455 rows x 4 columns]

## 4. Profiling DataFrames

### Displaying attribute names

In [ ]:
# TODO: print the names of the columns (attributes)
# ...

### Displaying the datatype of each column

In [ ]:
dataTypeSeries = df.dtypes
for col_idx in range(len(df.columns)):
    print(df.columns[col_idx], 'has type (', dataTypeSeries.iloc[col_idx], ')')

longitude has type ( float64 )
latitude has type ( float64 )
housing_median_age has type ( float64 )
total_rooms has type ( float64 )
total_bedrooms has type ( float64 )
population has type ( float64 )
households has type ( float64 )
median_income has type ( float64 )
median_house_value has type ( float64 )

### Displaying the number of unique values in each column

In [ ]:
for col in df.columns:
    print(col, 'has (', len(df[col].unique()), ') unique values')

longitude has ( 827 ) unique values
latitude has ( 840 ) unique values
housing_median_age has ( 52 ) unique values
total_rooms has ( 5533 ) unique values
total_bedrooms has ( 1848 ) unique values
population has ( 3683 ) unique values
households has ( 1740 ) unique values
median_income has ( 11175 ) unique values
median_house_value has ( 3694 ) unique values

### Numerical quantities

**TODO:** Print the minimum, maximum, average, and standard deviation of attributes with numerical datatypes.

In [ ]:
# TODO
# Hint: select numeric columns first, then use min(), max(), mean(), and std().

### Counting missing values

In [ ]:
s = df['longitude'].isnull()
s.sum()

np.int64(0)

**TODO:** Print each column name and the number of missing values in that column.

In [ ]:
# TODO
# ...

## 5. Connecting to an SQLite Database

The `sqlite3` library is included with Python and is available in Google Colab.

### Creating a connection to the database

In [ ]:
def create_connection(db_file):
    """Create a connection to the SQLite database specified by db_file."""
    conn = None
    try:
        conn = sqlite3.connect(db_file)
    except Error as e:
        print(e)
    return conn

### Querying the database

In [ ]:
def run_query(conn, query):
    """Execute a SQL query and return all result rows."""
    cur = conn.cursor()
    cur.execute(query)
    results = cur.fetchall()
    return results

### Creating a DataFrame from a database table

In [ ]:
def convert_db_table_to_DF(conn, table):
    # Get attribute names
    header_query = "SELECT name FROM pragma_table_info('" + table + "') ORDER BY cid;"
    cols_init = run_query(conn, header_query)
    cols = [cols_init[i][0] for i in range(len(cols_init))]

    # Get table records
    content_query = "SELECT * FROM " + table
    data = run_query(conn, content_query)

    return pd.DataFrame(data, columns=cols)

### Example: list the tables in the football database

In [ ]:
database = "sample_data/football.db"
conn = create_connection(database)

with conn:
    query = 'SELECT name FROM sqlite_schema WHERE type = "table"'
    data = run_query(conn, query)
    print(data)

[]

### Exercise: read the `game` table

**TODO:** Write code to read the data in the `game` table, store it in a DataFrame, and display the DataFrame.

In [ ]:
# TODO
# df_game = ...
# df_game

## 6. Merging DataFrames

This section practices operations analogous to union and join in relational algebra / SQL.

### Union of two DataFrames

**TODO:** Read `california_housing_train.csv` and `california_housing_test.csv` into `df_train` and `df_test`. Find their union and store it in `df_cal_housing`.

In [ ]:
# TODO
# df_train = ...
# df_test = ...
# df_cal_housing = ...
# df_cal_housing

### Joining two tables

**TODO:** Connect to the football database and read the `goal` (or `goals`, depending on the database schema) and `game` relations. Store them as `df_goal` and `df_game`, then join them into `df_goal_game`.

First inspect the column names to determine the appropriate join key.

In [ ]:
# TODO
# conn = create_connection("sample_data/football.db")
# df_goal = ...
# df_game = ...
# display(df_goal.head())
# display(df_game.head())
# df_goal_game = ...
# df_goal_game

## Optional: close the database connection

In [ ]:
# Run when you are finished with the database.
# conn.close()